src/main/resources/config/application-dev.yml, src/main/webapp/app/app.constants.ts, src/main/webapp/app/app.module.ts, src/main/webapp/app/entities/antecedents/antecedents.component.html, src/main/webapp/app/entities/antecedents/antecedents.component.ts, src/main/webapp/app/entities/antecedents/antecedents.module.ts, src/main/webapp/app/entities/antecedents/antecedents.route.ts, src/main/webapp/app/entities/antecedents/antecedents.service.ts, src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/app/shared/model/antecedents.model.ts, src/main/webapp/i18n/fr/global.json
Adding antécédents page to version 1
=> Adding antécédent page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/traitements-en-cours/traitement-en-cours.module.ts, src/main/webapp/app/entities/traitements-en-cours/traitement-en-cours.route.ts, src/main/webapp/app/entities/traitements-en-cours/traitement-en-cours.service.ts, src/main/webapp/app/entities/traitements-en-cours/traitements-en-cours.component.html, src/main/webapp/app/entities/traitements-en-cours/traitements-en-cours.component.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Add traitements en cours page into version 1
=> Adding traitements en cours page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/fiche-urgence/fiche-urgence.component.html, src/main/webapp/app/entities/fiche-urgence/fiche-urgence.component.ts, src/main/webapp/app/entities/fiche-urgence/fiche-urgence.module.ts, src/main/webapp/app/entities/fiche-urgence/fiche-urgence.route.ts, src/main/webapp/app/entities/fiche-urgence/fiche-urgence.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Add fiche d'urgence to version 1
=> Adding fiche d'urgence page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/suivi/suivi.component.html, src/main/webapp/app/entities/suivi/suivi.component.ts, src/main/webapp/app/entities/suivi/suivi.module.ts, src/main/webapp/app/entities/suivi/suivi.route.ts, src/main/webapp/app/entities/suivi/suivi.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Adding suivi page to version 1
=> Adding suivi page

src/main/webapp/app/entities/dmp/dmp.component.html, src/main/webapp/app/entities/dmp/dmp.component.ts, src/main/webapp/app/entities/dmp/dmp.module.ts, src/main/webapp/app/entities/dmp/dmp.route.ts, src/main/webapp/app/entities/dmp/dmp.service.ts, src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
=> Adding DMP page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/symptomes/symptomes.component.html, src/main/webapp/app/entities/symptomes/symptomes.component.ts, src/main/webapp/app/entities/symptomes/symptomes.module.ts, src/main/webapp/app/entities/symptomes/symptomes.route.ts, src/main/webapp/app/entities/symptomes/symptomes.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Adding symptoms page to version 1
=> Adding symptomes page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/traitement/traitement.component.html, src/main/webapp/app/entities/traitement/traitement.component.ts, src/main/webapp/app/entities/traitement/traitement.module.ts, src/main/webapp/app/entities/traitement/traitement.route.ts, src/main/webapp/app/entities/traitement/traitement.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Adding traitement page to version 1
=> Adding traitement page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/rdv/rdv.component.html, src/main/webapp/app/entities/rdv/rdv.component.ts, src/main/webapp/app/entities/rdv/rdv.module.ts, src/main/webapp/app/entities/rdv/rdv.route.ts, src/main/webapp/app/entities/rdv/rdv.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
=> Adding rdv page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/repercussions/repercussions.component.html, src/main/webapp/app/entities/repercussions/repercussions.component.ts, src/main/webapp/app/entities/repercussions/repercussions.module.ts, src/main/webapp/app/entities/repercussions/repercussions.route.ts, src/main/webapp/app/entities/repercussions/repercussions.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Adding repercussions page to version 1
=> Adding repercussions page

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/therapeutique/therapeutique.component.html, src/main/webapp/app/entities/therapeutique/therapeutique.component.ts, src/main/webapp/app/entities/therapeutique/therapeutique.module.ts, src/main/webapp/app/entities/therapeutique/therapeutique.route.ts, src/main/webapp/app/entities/therapeutique/therapeutique.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Adding thérapeutique page to version 1
=> Adding therapeutique page

src/main/webapp/app/entities/alertes/alertes.route.ts, src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
=> Adding alertes page

src/main/webapp/app/entities/articles/articles.component.html, src/main/webapp/app/entities/articles/articles.component.ts, src/main/webapp/app/entities/articles/articles.module.ts, src/main/webapp/app/entities/articles/articles.route.ts, src/main/webapp/app/entities/articles/articles.service.ts, src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/presentation/presentation.component.html, src/main/webapp/app/entities/presentation/presentation.component.ts, src/main/webapp/app/entities/presentation/presentation.module.ts, src/main/webapp/app/entities/presentation/presentation.route.ts, src/main/webapp/app/entities/presentation/presentation.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
Added presentation and articles pages to version 1
=> Add infos sed pages

src/main/webapp/app/entities/entity.module.ts, src/main/webapp/app/entities/faq/faq.component.html, src/main/webapp/app/entities/faq/faq.component.ts, src/main/webapp/app/entities/faq/faq.module.ts, src/main/webapp/app/entities/faq/faq.route.ts, src/main/webapp/app/entities/faq/faq.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/fr/global.json
=> Adding faq page

src/main/java/com/sed/app/web/rest/UserResource.java, src/main/webapp/app/app.constants.ts, src/main/webapp/app/core/user/account.model.ts, src/main/webapp/app/entities/symptomes/digestive/digestive.component.html, src/main/webapp/app/entities/symptomes/digestive/digestive.component.ts, src/main/webapp/app/entities/symptomes/digestive/digestives.service.ts, src/main/webapp/app/shared/model/digestive.ts
Added form with data labels to post digestive object to database
=> Added form to post data for digestive page

src/main/webapp/app/entities/symptomes/digestive/digestive.component.html, src/main/webapp/app/entities/symptomes/digestive/digestive.component.ts, src/main/webapp/app/entities/symptomes/digestive/digestives.service.ts
Added the possibility to update a form of the same day.
=> Added put option for the lastest form on the bdd of the same day.

src/main/java/com/sed/app/web/rest/UserResource.java, src/main/webapp/app/core/user/account.model.ts, src/main/webapp/app/entities/symptomes/digestive/digestive.component.ts, src/main/webapp/app/entities/symptomes/digestive/digestives.service.ts, src/main/webapp/app/shared/model/digestive.model.ts
Regarde si ça marche mieux maintenant
=> Debug POUR PAUL ET GUIGOU

src/main/webapp/app/entities/symptomes/musculaire/musculaire.component.html, src/main/webapp/app/entities/symptomes/musculaire/musculaire.component.ts, src/main/webapp/app/entities/symptomes/musculaire/musculaire.service.ts, src/main/webapp/app/shared/model/musculaire.model.ts
=> Page musculaire

src/main/java/com/sed/app/web/rest/UserResource.java, src/main/webapp/app/entities/symptomes/cardiovasculaire/cardiovasculaire.component.html, src/main/webapp/app/entities/symptomes/cardiovasculaire/cardiovasculaire.component.ts, src/main/webapp/app/entities/symptomes/cardiovasculaire/cardiovasculaire.service.ts, src/main/webapp/app/entities/symptomes/digestive/digestive.component.ts, src/main/webapp/app/entities/symptomes/symptomes.component.html, src/main/webapp/app/shared/model/cardiovasculaire.model.ts
Added cardioVasculaire form 
Modified names of buttons on Symptomes pages
Modified digestive component to prevent errors on console
=> Added cardioVasculaire form with add and modify options

src/main/webapp/app/entities/symptomes/digestive/digestive.component.ts, src/main/webapp/app/entities/symptomes/digestive/digestives.service.ts, src/main/webapp/app/entities/symptomes/musculaire/musculaire.component.ts, src/main/webapp/app/shared/model/digestive.model.ts
=> Debug pages

src/main/webapp/app/entities/symptomes/symptomes.component.ts, src/main/webapp/app/entities/traitement/traitement.component.html, src/main/webapp/app/entities/traitement/traitement.component.ts, src/main/webapp/app/entities/traitement/traitement.service.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/app/shared/model/traitement.model.ts, src/main/webapp/i18n/en/global.json, src/main/webapp/i18n/fr/global.json
Add translations for traitement page and form for traitement
=> Add traitements page

src/main/webapp/app/entities/symptomes/buccodentaire/buccodentaire.component.html, src/main/webapp/app/entities/symptomes/buccodentaire/buccodentaire.component.ts, src/main/webapp/app/entities/symptomes/buccodentaire/buccodentaire.service.ts, src/main/webapp/app/shared/model/buccodentaire.model.ts
Add buck dentaire page to version 1
=> Page buccodentaire OK

src/main/webapp/app/entities/symptomes/buccodentaire/buccodentaire.component.ts, src/main/webapp/app/entities/symptomes/buccodentaire/buccodentaire.service.ts
The service didn't scoped to the nice route on the API. 
So, manifestation digestives were catch.. Not bucco-dentaire.
=> Modified the buccodentaire service with the good route to the API !

src/main/webapp/app/entities/faq/faq.component.html, src/main/webapp/app/entities/faq/faq.component.ts
Add FAQ content to the version 1
=> Added content to the FAQ page

src/main/webapp/app/entities/symptomes/respiratoire/respiratoire.component.html, src/main/webapp/app/entities/symptomes/respiratoire/respiratoire.component.ts, src/main/webapp/app/entities/symptomes/respiratoire/respiratoire.service.ts, src/main/webapp/app/shared/model/respiratoire.model.ts
=> Added respiratoire page

src/main/java/com/sed/app/service/util/RandomUtil.java
---
This is a security fix for a  vulnerability in your [JHipster](https://www.jhipster.tech/) generated `RandomUtil.java` file(s).
Using one password reset token from your app combined with the POC below, an attacker can determine all future password reset tokens to be generated by this server. This allows an attacker to pick and choose what account they would like to takeover by sending account password reset requests for targeted accounts.
A version of JHipster Generator that was vulnerable to [CVE-2019-16303](https://github.com/jhipster/jhipster-kotlin/security/advisories/GHSA-j3rh-8vwq-wh84) was used to generate this project.
This version of JHipster generated code using an insecure source of randomness in security sensitive locations.
This class of vulnerability is better known as …
=> [SECURITY] CVE-2019-16303 - JHipster Vulnerability Fix - Use CSPRNG in RandomUtil
